create table "public"."subscriptions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "stripe_product_id_" text not null,
    "tolerence" smallint not null,
    "refresh_frequency" date not null,
    "price" smallint not null
);


alter table "public"."subscriptions" enable row level security;

create table "public"."user_metadata" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "first_name" text,
    "last_name" text,
    "profile_picture" text,
    "email" text,
    "phone" text,
    "description" text
);


alter table "public"."user_metadata" enable row level security;

create table "public"."user_subscriptions" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "type_" bigint not null,
    "expiry_date" date not null,
    "stripe_key" text not null,
    "should_expire" boolean not null default false
);


alter table "public"."user_subscriptions" enable row level security;

create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "username" text not null,
    "subscription" uuid not null,
    "credits" smallint default '0'::smallint,
    "metadata" uuid not null,
    "auth_id" uuid not null default gen_random_uuid(),
    "fcm_token" text
);


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX subscriptions_pkey ON public.subscriptions USING btree (id);

CREATE UNIQUE INDEX user_metadata_pkey ON public.user_metadata USING btree (id);

CREATE UNIQUE INDEX user_subscriptions_pkey ON public.user_subscriptions USING btree (id);

CREATE UNIQUE INDEX users_auth_id_key ON public.users USING btree (auth_id);

CREATE UNIQUE INDEX users_metadata_key ON public.users USING btree (metadata);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

CREATE UNIQUE INDEX users_subscription_key ON public.users USING btree (subscription);

CREATE UNIQUE INDEX users_username_key ON public.users USING btree (username);

alter table "public"."subscriptions" add constraint "subscriptions_pkey" PRIMARY KEY using index "subscriptions_pkey";

alter table "public"."user_metadata" add constraint "user_metadata_pkey" PRIMARY KEY using index "user_metadata_pkey";

alter table "public"."user_subscriptions" add constraint "user_subscriptions_pkey" PRIMARY KEY using index "user_subscriptions_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."user_subscriptions" add constraint "public_user_subscriptions_type__fkey" FOREIGN KEY (type_) REFERENCES subscriptions(id) not valid;

alter table "public"."user_subscriptions" validate constraint "public_user_subscriptions_type__fkey";

alter table "public"."users" add constraint "public_users_metadata_fkey" FOREIGN KEY (metadata) REFERENCES user_metadata(id) not valid;

alter table "public"."users" validate constraint "public_users_metadata_fkey";

alter table "public"."users" add constraint "public_users_subscription_fkey" FOREIGN KEY (subscription) REFERENCES user_subscriptions(id) not valid;

alter table "public"."users" validate constraint "public_users_subscription_fkey";

alter table "public"."users" add constraint "users_auth_id_key" UNIQUE using index "users_auth_id_key";

alter table "public"."users" add constraint "users_metadata_key" UNIQUE using index "users_metadata_key";

alter table "public"."users" add constraint "users_subscription_key" UNIQUE using index "users_subscription_key";

alter table "public"."users" add constraint "users_username_key" UNIQUE using index "users_username_key";

grant delete on table "public"."subscriptions" to "anon";

grant insert on table "public"."subscriptions" to "anon";

grant references on table "public"."subscriptions" to "anon";

grant select on table "public"."subscriptions" to "anon";

grant trigger on table "public"."subscriptions" to "anon";

grant truncate on table "public"."subscriptions" to "anon";

grant update on table "public"."subscriptions" to "anon";

grant delete on table "public"."subscriptions" to "authenticated";

grant insert on table "public"."subscriptions" to "authenticated";

grant references on table "public"."subscriptions" to "authenticated";

grant select on table "public"."subscriptions" to "authenticated";

grant trigger on table "public"."subscriptions" to "authenticated";

grant truncate on table "public"."subscriptions" to "authenticated";

grant update on table "public"."subscriptions" to "authenticated";

grant delete on table "public"."subscriptions" to "service_role";

grant insert on table "public"."subscriptions" to "service_role";

grant references on table "public"."subscriptions" to "service_role";

grant select on table "public"."subscriptions" to "service_role";

grant trigger on table "public"."subscriptions" to "service_role";

grant truncate on table "public"."subscriptions" to "service_role";

grant update on table "public"."subscriptions" to "service_role";

grant delete on table "public"."user_metadata" to "anon";

grant insert on table "public"."user_metadata" to "anon";

grant references on table "public"."user_metadata" to "anon";

grant select on table "public"."user_metadata" to "anon";

grant trigger on table "public"."user_metadata" to "anon";

grant truncate on table "public"."user_metadata" to "anon";

grant update on table "public"."user_metadata" to "anon";

grant delete on table "public"."user_metadata" to "authenticated";

grant insert on table "public"."user_metadata" to "authenticated";

grant references on table "public"."user_metadata" to "authenticated";

grant select on table "public"."user_metadata" to "authenticated";

grant trigger on table "public"."user_metadata" to "authenticated";

grant truncate on table "public"."user_metadata" to "authenticated";

grant update on table "public"."user_metadata" to "authenticated";

grant delete on table "public"."user_metadata" to "service_role";

grant insert on table "public"."user_metadata" to "service_role";

grant references on table "public"."user_metadata" to "service_role";

grant select on table "public"."user_metadata" to "service_role";

grant trigger on table "public"."user_metadata" to "service_role";

grant truncate on table "public"."user_metadata" to "service_role";

grant update on table "public"."user_metadata" to "service_role";

grant delete on table "public"."user_subscriptions" to "anon";

grant insert on table "public"."user_subscriptions" to "anon";

grant references on table "public"."user_subscriptions" to "anon";

grant select on table "public"."user_subscriptions" to "anon";

grant trigger on table "public"."user_subscriptions" to "anon";

grant truncate on table "public"."user_subscriptions" to "anon";

grant update on table "public"."user_subscriptions" to "anon";

grant delete on table "public"."user_subscriptions" to "authenticated";

grant insert on table "public"."user_subscriptions" to "authenticated";

grant references on table "public"."user_subscriptions" to "authenticated";

grant select on table "public"."user_subscriptions" to "authenticated";

grant trigger on table "public"."user_subscriptions" to "authenticated";

grant truncate on table "public"."user_subscriptions" to "authenticated";

grant update on table "public"."user_subscriptions" to "authenticated";

grant delete on table "public"."user_subscriptions" to "service_role";

grant insert on table "public"."user_subscriptions" to "service_role";

grant references on table "public"."user_subscriptions" to "service_role";

grant select on table "public"."user_subscriptions" to "service_role";

grant trigger on table "public"."user_subscriptions" to "service_role";

grant truncate on table "public"."user_subscriptions" to "service_role";

grant update on table "public"."user_subscriptions" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";


